$(function () {
    $('#div0002').highcharts({
        chart: { zoomType: true, events: { load: function (event) { var chartOb = this; } } },
        credits: { enabled: false }, exporting: { enabled: false }, tooltip: { enabled: true }, title: {
            text: 'Corte de Hoja', style: { fontFamily: 'Verdana, sans-serif' }
        }, subtitle: { text: '', style: { fontFamily: 'Verdana, sans-serif' } }, xAxis: [{ fffordinal: true, categories: ['25'], crosshair: true, title: { text: 'Week' } }], yAxis: [{ labels: { format: '{value} Hrs', style: { color: '#000000' } }, title: { text: 'Hours', style: { color: '#000000' } } }, { labels: { format: '{value} ', style: { color: '#4F81BD' } }, title: { text: '', style: { color: '#000000' } }, labels: { format: '{value}', style: { color: '#000000' }, enabled: true }, opposite: true }], plotOptions: { column: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.2f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif' } }, marker: { enabled: true }, enableMouseTracking: true }, spline: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.0f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif', dashStyle: 'line' } }, marker: { enabled: false } } }, series: [{ name: 'Capacity', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [{ y: 45, color: '#6390C5' }] }, { name: 'Scheduled Hrs', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [40] }]
    });

    $('#div0001').highcharts({
        chart: { zoomType: true, events: { load: function (event) { var chartOb = this; } } }, credits: { enabled: false }, exporting: { enabled: false }, tooltip: { enabled: true },
        title: {
            text: 'Corte de Rollo a Hoja', style: { fontFamily: 'Verdana, sans-serif' }
        }, subtitle: { text: '', style: { fontFamily: 'Verdana, sans-serif' } }, xAxis: [{ fffordinal: true, categories: ['25', '26'], crosshair: true, title: { text: 'Week' } }], yAxis: [{ labels: { format: '{value} Hrs', style: { color: '#000000' } }, title: { text: 'Hours', style: { color: '#000000' } } }, { labels: { format: '{value} ', style: { color: '#4F81BD' } }, title: { text: '', style: { color: '#000000' } }, labels: { format: '{value}', style: { color: '#000000' }, enabled: true }, opposite: true }], plotOptions: { column: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.2f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif' } }, marker: { enabled: true }, enableMouseTracking: true }, spline: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.0f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif', dashStyle: 'line' } }, marker: { enabled: false } } }, series: [{ name: 'Capacity', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [{ y: 45, color: '#6390C5' }, { y: 77, color: '#6390C5' }] }, { name: 'Scheduled Hrs', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [42, 46] }]
    }); $('#div0001').highcharts({
        chart:
            { zoomType: true, events: { load: function (event) { var chartOb = this; } } }, credits: { enabled: false }, exporting: { enabled: false }, tooltip: { enabled: true }, title: { text: 'Corte de Rollo a Hoja', style: { fontFamily: 'Verdana, sans-serif' } }, subtitle: { text: '', style: { fontFamily: 'Verdana, sans-serif' } }, xAxis: [{ fffordinal: true, categories: ['25', '26'], crosshair: true, title: { text: 'Week' } }], yAxis: [{ labels: { format: '{value} Hrs', style: { color: '#000000' } }, title: { text: 'Hours', style: { color: '#000000' } } }, { labels: { format: '{value} ', style: { color: '#4F81BD' } }, title: { text: '', style: { color: '#000000' } }, labels: { format: '{value}', style: { color: '#000000' }, enabled: true }, opposite: true }], plotOptions: { column: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.2f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif' } }, marker: { enabled: true }, enableMouseTracking: true }, spline: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.0f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif', dashStyle: 'line' } }, marker: { enabled: false } } }, series: [{ name: 'Capacity', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [{ y: 45, color: '#6390C5' }, { y: 77, color: '#6390C5' }] }, { name: 'Scheduled Hrs', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [42, 46] }]
    });

    $('#divPLA01').highcharts({
        chart: {
            zoomType: true, events: {
                load: function (event) { var chartOb = this; }
            }
        }, credits: { enabled: false }, exporting: { enabled: false }, tooltip: { enabled: true }, title: {
            text: 'Corte Oxy-Plasma HD', style: { fontFamily: 'Verdana, sans-serif' }
        }, subtitle: { text: '', style: { fontFamily: 'Verdana, sans-serif' } }, xAxis: [{ fffordinal: true, categories: ['25', '26'], crosshair: true, title: { text: 'Week' } }], yAxis: [{ labels: { format: '{value} Hrs', style: { color: '#000000' } }, title: { text: 'Hours', style: { color: '#000000' } } }, { labels: { format: '{value} ', style: { color: '#4F81BD' } }, title: { text: '', style: { color: '#000000' } }, labels: { format: '{value}', style: { color: '#000000' }, enabled: true }, opposite: true }], plotOptions: { column: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.2f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif' } }, marker: { enabled: true }, enableMouseTracking: true }, spline: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.0f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif', dashStyle: 'line' } }, marker: { enabled: false } } }, series: [{ name: 'Capacity', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [{ y: 99, color: '#6390C5' }, { y: 87, color: '#6390C5' }] }, { name: 'Scheduled Hrs', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [63, 81] }]
    }); $('#divPLA01').highcharts({
        chart: { zoomType: true, events: { load: function (event) { var chartOb = this; } } }, credits: { enabled: false }, exporting: { enabled: false }, tooltip: { enabled: true }, title: { text: 'Corte Oxy-Plasma HD', style: { fontFamily: 'Verdana, sans-serif' } }, subtitle: { text: '', style: { fontFamily: 'Verdana, sans-serif' } }, xAxis: [{ fffordinal: true, categories: ['25', '26'], crosshair: true, title: { text: 'Week' } }], yAxis: [{ labels: { format: '{value} Hrs', style: { color: '#000000' } }, title: { text: 'Hours', style: { color: '#000000' } } }, { labels: { format: '{value} ', style: { color: '#4F81BD' } }, title: { text: '', style: { color: '#000000' } }, labels: { format: '{value}', style: { color: '#000000' }, enabled: true }, opposite: true }], plotOptions: { column: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.2f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif' } }, marker: { enabled: true }, enableMouseTracking: true }, spline: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.0f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif', dashStyle: 'line' } }, marker: { enabled: false } } }, series: [{ name: 'Capacity', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [{ y: 99, color: '#6390C5' }, { y: 87, color: '#6390C5' }] }, { name: 'Scheduled Hrs', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [63, 81] }]
    }); $('#divLSR1').highcharts({
        chart: { zoomType: true, events: { load: function (event) { var chartOb = this; } } }, credits: { enabled: false }, exporting: { enabled: false }, tooltip: { enabled: true }, title: { text: 'Laser 1', style: { fontFamily: 'Verdana, sans-serif' } }, subtitle: { text: '', style: { fontFamily: 'Verdana, sans-serif' } }, xAxis: [{ fffordinal: true, categories: ['25', '26'], crosshair: true, title: { text: 'Week' } }], yAxis: [{ labels: { format: '{value} Hrs', style: { color: '#000000' } }, title: { text: 'Hours', style: { color: '#000000' } } }, { labels: { format: '{value} ', style: { color: '#4F81BD' } }, title: { text: '', style: { color: '#000000' } }, labels: { format: '{value}', style: { color: '#000000' }, enabled: true }, opposite: true }], plotOptions: { column: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.2f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif' } }, marker: { enabled: true }, enableMouseTracking: true }, spline: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.0f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif', dashStyle: 'line' } }, marker: { enabled: false } } }, series: [{ name: 'Capacity', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [{ y: 110, color: '#6390C5' }, { y: 92, color: '#6390C5' }] }, { name: 'Scheduled Hrs', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [96, 30] }]
    }); $('#divLSR1').highcharts({
        chart: { zoomType: true, events: { load: function (event) { var chartOb = this; } } }, credits: { enabled: false }, exporting: { enabled: false }, tooltip: { enabled: true }, title: { text: 'Laser 1', style: { fontFamily: 'Verdana, sans-serif' } }, subtitle: { text: '', style: { fontFamily: 'Verdana, sans-serif' } }, xAxis: [{ fffordinal: true, categories: ['25', '26'], crosshair: true, title: { text: 'Week' } }], yAxis: [{ labels: { format: '{value} Hrs', style: { color: '#000000' } }, title: { text: 'Hours', style: { color: '#000000' } } }, { labels: { format: '{value} ', style: { color: '#4F81BD' } }, title: { text: '', style: { color: '#000000' } }, labels: { format: '{value}', style: { color: '#000000' }, enabled: true }, opposite: true }], plotOptions: { column: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.2f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif' } }, marker: { enabled: true }, enableMouseTracking: true }, spline: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.0f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif', dashStyle: 'line' } }, marker: { enabled: false } } }, series: [{ name: 'Capacity', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [{ y: 110, color: '#6390C5' }, { y: 92, color: '#6390C5' }] }, { name: 'Scheduled Hrs', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [96, 30] }]
    }); $('#divLSR2').highcharts({
        chart: { zoomType: true, events: { load: function (event) { var chartOb = this; } } }, credits: { enabled: false }, exporting: { enabled: false }, tooltip: { enabled: true }, title: { text: 'Laser 2', style: { fontFamily: 'Verdana, sans-serif' } }, subtitle: { text: '', style: { fontFamily: 'Verdana, sans-serif' } }, xAxis: [{ fffordinal: true, categories: ['25', '26'], crosshair: true, title: { text: 'Week' } }], yAxis: [{ labels: { format: '{value} Hrs', style: { color: '#000000' } }, title: { text: 'Hours', style: { color: '#000000' } } }, { labels: { format: '{value} ', style: { color: '#4F81BD' } }, title: { text: '', style: { color: '#000000' } }, labels: { format: '{value}', style: { color: '#000000' }, enabled: true }, opposite: true }], plotOptions: { column: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.2f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif' } }, marker: { enabled: true }, enableMouseTracking: true }, spline: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.0f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif', dashStyle: 'line' } }, marker: { enabled: false } } }, series: [{ name: 'Capacity', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [{ y: 109, color: '#6390C5' }, { y: 92, color: '#6390C5' }] }, { name: 'Scheduled Hrs', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [99, 23] }]
    }); $('#divLSR2').highcharts({
        chart: { zoomType: true, events: { load: function (event) { var chartOb = this; } } }, credits: { enabled: false }, exporting: { enabled: false }, tooltip: { enabled: true }, title: { text: 'Laser 2', style: { fontFamily: 'Verdana, sans-serif' } }, subtitle: { text: '', style: { fontFamily: 'Verdana, sans-serif' } }, xAxis: [{ fffordinal: true, categories: ['25', '26'], crosshair: true, title: { text: 'Week' } }], yAxis: [{ labels: { format: '{value} Hrs', style: { color: '#000000' } }, title: { text: 'Hours', style: { color: '#000000' } } }, { labels: { format: '{value} ', style: { color: '#4F81BD' } }, title: { text: '', style: { color: '#000000' } }, labels: { format: '{value}', style: { color: '#000000' }, enabled: true }, opposite: true }], plotOptions: { column: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.2f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif' } }, marker: { enabled: true }, enableMouseTracking: true }, spline: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.0f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif', dashStyle: 'line' } }, marker: { enabled: false } } }, series: [{ name: 'Capacity', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [{ y: 109, color: '#6390C5' }, { y: 92, color: '#6390C5' }] }, { name: 'Scheduled Hrs', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [99, 23] }]
    });
    $('#divLSR3').highcharts({
        chart: { zoomType: true, events: { load: function (event) { var chartOb = this; } } }, credits: { enabled: false }, exporting: { enabled: false }, tooltip: { enabled: true }, title: { text: 'Laser 3', style: { fontFamily: 'Verdana, sans-serif' } }, subtitle: { text: '', style: { fontFamily: 'Verdana, sans-serif' } }, xAxis: [{ fffordinal: true, categories: ['25', '26'], crosshair: true, title: { text: 'Week' } }], yAxis: [{ labels: { format: '{value} Hrs', style: { color: '#000000' } }, title: { text: 'Hours', style: { color: '#000000' } } }, { labels: { format: '{value} ', style: { color: '#4F81BD' } }, title: { text: '', style: { color: '#000000' } }, labels: { format: '{value}', style: { color: '#000000' }, enabled: true }, opposite: true }], plotOptions: { column: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.2f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif' } }, marker: { enabled: true }, enableMouseTracking: true }, spline: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.0f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif', dashStyle: 'line' } }, marker: { enabled: false } } }, series: [{ name: 'Capacity', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [{ y: 109, color: '#6390C5' }, { y: 92, color: '#6390C5' }] }, { name: 'Scheduled Hrs', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [106, 33] }]
    }); $('#divLSR3').highcharts({ 
        chart: { zoomType: true, events: { load: function (event) { var chartOb = this; } } }, credits: { enabled: false }, exporting: { enabled: false }, tooltip: { enabled: true }, title: { text: 'Laser 3', style: { fontFamily: 'Verdana, sans-serif' } }, subtitle: { text: '', style: { fontFamily: 'Verdana, sans-serif' } }, xAxis: [{ fffordinal: true, categories: ['25', '26'], crosshair: true, title: { text: 'Week' } }], yAxis: [{ labels: { format: '{value} Hrs', style: { color: '#000000' } }, title: { text: 'Hours', style: { color: '#000000' } } }, { labels: { format: '{value} ', style: { color: '#4F81BD' } }, title: { text: '', style: { color: '#000000' } }, labels: { format: '{value}', style: { color: '#000000' }, enabled: true }, opposite: true }], plotOptions: { column: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.2f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif' } }, marker: { enabled: true }, enableMouseTracking: true }, spline: { dataLabels: { enabled: true, color: '#34495e', align: 'center', format: '{point.y:.0f}', style: { fontSize: '9px', fontFamily: 'Verdana, sans-serif', dashStyle: 'line' } }, marker: { enabled: false } } }, series: [{ name: 'Capacity', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [{ y: 109, color: '#6390C5' }, { y: 92, color: '#6390C5' }] }, { name: 'Scheduled Hrs', type: 'column', yAxis: 0, marker: { enabled: 1, }, color: '#6390C5', dashStyle: '', tooltip: { valueSuffix: ' ' }, data: [106, 33] }] });
});